version: "3.3"

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped

    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.myweb.address=:3333"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=anatolii@liniad.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3333:3333"

    security_opt:
      - no-new-privileges:true

    # labels:
    #   - "traefik.enable=true"
    #   - "--log.level=DEBUG"
    # env_file:
    #   - .env
    networks:
      - proxy


  whoami:
    image: "traefik/whoami"
    container_name: "simple-service1"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      # - "traefik.http.routers.whoami.entrypoints=websecure"
      # - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=myweb"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # - "traefik.http.services.whoami.loadbalancer.server.port=10101"
    ports:
      - "88:80"

    networks:
      - proxy

#Docker Networks
networks:
  proxy:
    name: "traefik_proxy"
    external: true